name: CI/CD

on:
  push:
    tags:
      - "*.*.*"
      - "*.*.*-*.*"
  workflow_dispatch:
    inputs:
      environment:
        description: 'Development Environment'
        required: true
        default: 'test'
        type: choice
        options:
          - test
          - production

env:
  SHOULD_RUN: ${{ github.event_name == 'push' || github.event.inputs.environment != '' }}

jobs:
  build_docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    if: ${{ env.SHOULD_RUN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect changed packages
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            frontend:
              - 'packages/frontend/**'
            backend:
              - 'packages/backend/**'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # === FRONTEND ===
      - name: Docker meta (frontend)
        id: meta-frontend
        if: steps.changes.outputs.frontend == 'true'
        uses: docker/metadata-action@v5
        with:
          images: |
            vastsea/vastsea-sso-frontend
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest
            ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'test' && 'type=raw,value=test' || '' }}
            type=raw,value=${{ github.sha }}

      - name: Build and push frontend
        if: steps.changes.outputs.frontend == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./packages/frontend
          file: ./packages/frontend/dockerfile
          push: true
          tags: ${{ steps.meta-frontend.outputs.tags }}
          labels: ${{ steps.meta-frontend.outputs.labels }}
          build-args: |
            BASE_URL=${{ vars.BASE_URL }}
            AUTH_SERVER_CLIENT_ID=${{ secrets.AUTH_SERVER_CLIENT_ID }}
            VITE_AUTH_SERVER_CLIENT_ID=${{ vars.VITE_AUTH_SERVER_CLIENT_ID }}
            VITE_GT_ID=${{ vars.VITE_GT_ID }}

      # === BACKEND ===
      - name: Docker meta (backend)
        id: meta-backend
        if: steps.changes.outputs.backend == 'true'
        uses: docker/metadata-action@v5
        with:
          images: |
            vastsea/vastsea-sso-backend
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest
            ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'test' && 'type=raw,value=test' || '' }}
            type=raw,value=${{ github.sha }}

      - name: Build and push backend
        if: steps.changes.outputs.backend == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./packages/backend
          file: ./packages/backend/dockerfile
          push: true
          tags: ${{ steps.meta-backend.outputs.tags }}
          labels: ${{ steps.meta-backend.outputs.labels }}
